# -*- coding: utf-8 -*-
"""Spect.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11iupLvHCNlFN0o8OCOjIFvPaN4by7Ckl
"""

import librosa
import librosa.display
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

y, sr = librosa.load('/content/drive/MyDrive/finalyear/speaker_diarization/join.wav')
plt.plot(y);
plt.title('Signal');
plt.xlabel('Time (samples)');
plt.ylabel('Amplitude');

import numpy as np
n_fft = 2048
ft = np.abs(librosa.stft(y[:n_fft], hop_length = n_fft+1))
plt.plot(ft);
plt.title('Spectrum');
plt.xlabel('Frequency Bin');
plt.ylabel('Amplitude');

spec = np.abs(librosa.stft(y, hop_length=512))
spec = librosa.amplitude_to_db(spec, ref=np.max)
librosa.display.specshow(spec, sr=sr, x_axis='time', y_axis='log');
plt.colorbar(format='%+2.0f dB');
plt.title('Spectrogram');